export const PINPAD_CONNECTING = 'PINPAD_CONNECTING';
export const PINPAD_CONNECTED = 'PINPAD_CONNECTED';
export const PINPAD_CLOSING_CONNECTION = 'PINPAD_CLOSING_CONNECTION';
export const PINPAD_OFFLINE = 'PINPAD_OFFLINE';
