export const UPDATE_HMAC_CLIENT_ID = 'UPDATE_HMAC_CLIENT_ID';
export const UPDATE_HMAC_CLIENT_TOKEN = 'UPDATE_HMAC_CLIENT_TOKEN';
export const UPDATE_HMAC_CLIENT_TIMESTAMP = 'UPDATE_HMAC_CLIENT_TIMESTAMP';
