export const UPDATE_PRIMARY_ACCOUNT_NUMBER = 'UPDATE_PRIMARY_ACCOUNT_NUMBER';
export const UPDATE_EXPIRY_DATE = 'UPDATE_EXPIRY_DATE';
export const UPDATE_SECURITY_CODE = 'UPDATE_SECURITY_CODE';
export const UPDATE_BUYER_ID = 'UPDATE_BUYER_ID';
export const UPDATE_ZIP_CODE = 'UPDATE_ZIP_CODE';
export const UPDATE_DOB = 'UPDATE_DOB';
export const UPDATE_ENCRYPTED_PIN = 'UPDATE_ENCRYPTED_PIN';
export const UPDATE_DUKPT_SMID = 'UPDATE_DUKPT_SMID';
export const UPDATE_POS_ENTRY_MODE = 'UPDATE_POS_ENTRY_MODE';
export const UPDATE_CARD_SEQUENCE_NUMBER = 'UPDATE_CARD_SEQUENCE_NUMBER';
export const UPDATE_EMV_TAGS_GO_ONLINE = 'UPDATE_EMV_TAGS_GO_ONLINE';
export const UPDATE_EMV_TAGS_FROM_HOST = 'UPDATE_EMV_TAGS_FROM_HOST';
export const UPDATE_ETB_STRING = 'UPDATE_ETB_STRING';
export const UPDATE_TRACK1_DATA = 'UPDATE_TRACK1_DATA';
export const UPDATE_TRACK2_DATA = 'UPDATE_TRACK2_DATA';
export const UPDATE_PURCHASE_ORDER = 'UPDATE_PURCHASE_ORDER';
export const MAKING_PINPAD_XREF_REQUEST = 'MAKING_PINPAD_XREF_REQUEST';
export const RECEIVE_PINPAD_XREF_SUCCESS = 'RECEIVE_PINPAD_XREF_SUCCESS';
export const RECEIVE_PINPAD_XREF_FAILURE = 'RECEIVE_PINPAD_XREF_FAILURE';
export const MAKING_PINPAD_CREDIT_AUTH_REQUEST = 'MAKING_PINPAD_CREDIT_AUTH_REQUEST';
export const MAKING_PINPAD_CREDIT_AUTH_SIMPLE_REVERSAL_REQUEST =
  'MAKING_PINPAD_CREDIT_AUTH_SIMPLE_REVERSAL_REQUEST';
export const RECEIVE_PINPAD_CREDIT_AUTH_REVERSAL_SUCCESS =
  'RECEIVE_PINPAD_CREDIT_AUTH_REVERSAL_SUCCESS';
export const RECEIVE_PINPAD_CREDIT_AUTH_REVERSAL_FAILURE =
  'RECEIVE_PINPAD_CREDIT_AUTH_REVERSAL_FAILURE';
export const RECEIVE_PINPAD_CREDIT_AUTH_SUCCESS = 'RECEIVE_PINPAD_CREDIT_AUTH_SUCCESS';
export const RECEIVE_PINPAD_CREDIT_AUTH_FAILURE = 'RECEIVE_PINPAD_CREDIT_AUTH_FAILURE';
export const RESET_CARD_DETAILS = 'RESET_CARD_DETAILS';
