export const UPDATE_ZIP_CODE = 'UPDATE_ZIP_CODE';
export const UPDATE_DOB = 'UPDATE_DOB';
export const UPDATE_SSN = 'UPDATE_SSN';
export const UPDATE_PHONE_NUMBER = 'UPDATE_PHONE_NUMBER';
export const RESET_CARD_DETAILS = 'RESET_CARD_DETAILS';
