export const UPDATE_ADDRESS__LINE_1 = 'UPDATE_ADDRESS__LINE_1';
export const UPDATE_ADDRESS__LINE_2 = 'UPDATE_ADDRESS__LINE_2';
export const UPDATE_ADDRESS__CITY = 'UPDATE_ADDRESS__CITY';
export const UPDATE_ADDRESS__STATE = 'UPDATE_ADDRESS__STATE';
export const UPDATE_ADDRESS__ZIP_CODE = 'UPDATE_ADDRESS__ZIP_CODE';
export const UPDATE_ADDRESS__COUNTRY_CODE = 'UPDATE_ADDRESS__COUNTRY_CODE';
